# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'hpd_ios_demos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hpd_ios_demos
  pod 'SnapKit'
  pod 'Then'
  # RX
  pod 'RxSwift'
  pod 'RxGesture'
  
  pod "SkeletonView"
  
  pod 'BMPlayer'
  
  # 欢拓
  pod 'AgoraRtcEngine_iOS','~> 3.0.0' #SDK使用
  pod 'TalkfunMediaFramework','~> 2.1.0' #SDK使用
  pod 'Socket.IO-Client-Swift', '~> 15.1.0' #SDK使用
  pod 'MJExtension', '~> 3.0.13' #SDK使用
  # 欢拓
  pod 'YZAppSDK'

  target 'hpd_ios_demosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hpd_ios_demosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
