# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'hpd_ios_demos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hpd_ios_demos
  pod 'SnapKit'
  pod 'Then'
  # RX
  pod 'RxSwift'
  pod 'RxGesture'
  
  pod "SkeletonView"
  
  pod 'BMPlayer'

  target 'hpd_ios_demosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hpd_ios_demosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
